// 메인 페이지 산업군 정보 조회 쿼리 + 산업군 상세 정보 페이지 산업군 상세정보, 기업정보 쿼리 성능테스트
// 테스트는 스프링 AOP LogAspect 기반으로 LogExecutionTime 에너테이션 붙은 메서드만 테스트 대상임.

# 모든 산업군 조회
GET http://127.0.0.1:80/
Accept: application/json
###

# 산업군 세부정보 + 기업정보 조회
GET http://127.0.0.1:80/industry-detail
Accept: application/json
###
